name: first-workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting again
        run: echo "hello again"
      - name: print gain
        run: |
            echo "again"
            echo "please"
